import {
  pgTable,
  serial,
  text,
  timestamp,
  varchar,
  jsonb,
} from "drizzle-orm/pg-core";

export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  clerkId: varchar("clerk_id", { length: 255 }).notNull().unique(),
  email: varchar("email", { length: 255 }).notNull().unique(),
  name: varchar("name", { length: 255 }).notNull(),
  username: varchar("username", { length: 255 }).unique(),
  profileImageUrl: text("profile_image_url"),
  coverImageUrl: text("cover_image_url"),
  publicEmail: varchar("public_email", { length: 255 }),
  phoneNumber: varchar("phone_number", { length: 50 }),
  whatsappPhoneNumber: varchar("whatsapp_phone_number", { length: 50 }),
  whatsappConsentAt: timestamp("whatsapp_consent_at"),
  tagline: varchar("tagline", { length: 160 }),
  bio: text("bio"),
  websiteUrl: varchar("website_url", { length: 255 }),
  socials: jsonb("socials"),
  location: jsonb("location"),
  preferredCurrency: varchar("preferred_currency", { length: 3 }),
  timezone: varchar("timezone", { length: 100 }),
  preferences: jsonb("preferences"),
  status: varchar("status", { length: 20 }).default("ok").notNull(),
  suspendedAt: timestamp("suspended_at"),
  suspendedReason: text("suspended_reason"),
  createdAt: timestamp("created_at").defaultNow(),
});
